services:
  app:
    build:
      context: .
      dockerfile: ATM.Backend.Api/Dockerfile
    container_name: atm-backend-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=MultibancoDB;User Id=sa;Password=StrongP@ssw0rd123;TrustServerCertificate=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - atm-network
    restart: on-failure

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: atm-sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongP@ssw0rd123
    ports:
      - "1433:1433"
    networks:
      - atm-network
    volumes:
      - sqlvolume:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "StrongP@ssw0rd123" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  atm-network:
    driver: bridge

volumes:
  sqlvolume: